version: "3.5"
services:
  app:
    restart: always
    image: "django-eshop-main-app"
    command: bash -c "
                      python3 manage.py collectstatic --noinput &&
                      python3 manage.py makemigrations &&
                      python3 manage.py migrate &&
                      gunicorn --timeout=30 --workers=1 --bind :443 --bind :80 django_shop_main_app.wsgi:application"
    volumes:
      - .:/code
      - static-volume:/code/collected_static
      - media-volume:/code/media
    expose:
      - "443"
      - "80"
    depends_on:
      - db
    networks:
      - web_network
      - db_network
  db:
    image: "postgres"
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB:
      - POSTGRES_USER:
      - POSTGRES_PASSWORD:
      # - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - db_network
    
  nginx:
    build: ./nginx
    volumes: 
      - static-volume:/code/collected_static
      - media-volume:/code/media
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on: 
      - app
    networks: 
      - web_network

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  static-volume:
  media-volume:
  database-data: