# Generated by Django 3.1.3 on 2020-12-26 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201224_0948'),
        ('payment', '0002_ecpay_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecpay_payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.order'),
        ),
    ]
