# Generated by Django 3.1.3 on 2020-12-26 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201224_0948'),
        ('payment', '0004_auto_20201226_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecpay_payment',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.order'),
        ),
    ]
