# Generated by Django 3.1.3 on 2021-01-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10, verbose_name='名稱')),
                ('line_id', models.CharField(default='', max_length=60, verbose_name='line_id')),
                ('actived', models.BooleanField(default=False, verbose_name='啟用')),
            ],
            options={
                'verbose_name': '會員',
                'verbose_name_plural': '會員',
                'ordering': ('name',),
            },
        ),
    ]
