# Generated by Django 3.1.3 on 2021-01-04 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='VIP_User',
        ),
    ]
