# Generated by Django 3.1.3 on 2020-11-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page_content',
            name='slug',
            field=models.CharField(default='請設定', max_length=100, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='page_content',
            name='name',
            field=models.CharField(default='請設定', max_length=100, unique=True, verbose_name='項目'),
        ),
    ]
